//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSGAMT2010.PS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TSGAInfo", Namespace="http://schemas.datacontract.org/2004/07/TSGALibrary")]
    [System.SerializableAttribute()]
    public partial class TSGAInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BestPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PathIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BestPath {
            get {
                return this.BestPathField;
            }
            set {
                if ((this.BestPathField.Equals(value) != true)) {
                    this.BestPathField = value;
                    this.RaisePropertyChanged("BestPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PathId {
            get {
                return this.PathIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PathIdField, value) != true)) {
                    this.PathIdField = value;
                    this.RaisePropertyChanged("PathId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PS.IChanges", CallbackContract=typeof(TSGAMT2010.PS.IChangesCallback))]
    public interface IChanges {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChanges/SubscribeToResultChange", ReplyAction="http://tempuri.org/IChanges/SubscribeToResultChangeResponse")]
        bool SubscribeToResultChange(int triggersolution, string pathId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IChanges/UnSubscribeToResultChange", ReplyAction="http://tempuri.org/IChanges/UnSubscribeToResultChangeResponse")]
        bool UnSubscribeToResultChange();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChangesCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChanges/OnBestPathChange")]
        void OnBestPathChange(TSGAMT2010.PS.TSGAInfo tinfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChangesChannel : TSGAMT2010.PS.IChanges, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChangesClient : System.ServiceModel.DuplexClientBase<TSGAMT2010.PS.IChanges>, TSGAMT2010.PS.IChanges {
        
        public ChangesClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ChangesClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ChangesClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ChangesClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ChangesClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public bool SubscribeToResultChange(int triggersolution, string pathId) {
            return base.Channel.SubscribeToResultChange(triggersolution, pathId);
        }
        
        public bool UnSubscribeToResultChange() {
            return base.Channel.UnSubscribeToResultChange();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PS.IPathChanged")]
    public interface IPathChanged {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPathChanged/ChangePath", ReplyAction="http://tempuri.org/IPathChanged/ChangePathResponse")]
        bool ChangePath(int bestPath, string pathId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPathChangedChannel : TSGAMT2010.PS.IPathChanged, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PathChangedClient : System.ServiceModel.ClientBase<TSGAMT2010.PS.IPathChanged>, TSGAMT2010.PS.IPathChanged {
        
        public PathChangedClient() {
        }
        
        public PathChangedClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PathChangedClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PathChangedClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PathChangedClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ChangePath(int bestPath, string pathId) {
            return base.Channel.ChangePath(bestPath, pathId);
        }
    }
}
